### ISSUE TITLE
TypeError: Ascii is not a constructor

### ISSUE THREAD

**Issue by agirorn** [guo-yu/ascii#9]
When I tried out the example in the README just get an error
```js
/home/agirorn/code-play/logo/logo.js:2
var pic = new Ascii('logo.png');
          ^

TypeError: Ascii is not a constructor
    at Object.<anonymous> (/home/agirorn/code-play/logo/logo.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

```shell
➜  logo node
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> var Ascii = require('ascii');
undefined
> Ascii.toString()
'[object Object]'
> 
```

**Comment by bgracz** [comment]
Did you found solution?

**Comment by agirorn** [comment]
No, I just wanted to let you know this was not the best out of the box experience so you could look into it.
